---
esphome:
  name: restfan
  upper_devicename: RESTfan
  platform: ESP8266
  board: d1_mini
  includes:
    - restfan.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:

output:
  - platform: custom
    type: float
    outputs:
      id: fanspeed_output
    lambda: |-
      auto rest_fan = new RestFanOutput();
      App.register_component(rest_fan);
      return {rest_fan};

  - platform: gpio
    pin: GPIO2
    id: oscillation_output

fan:
  - platform: speed
    output: fanspeed_output
    oscillation_output: oscillation_output 
    speed_count: 3
    id: restfan
    name: "RESTfan"
